# action.yaml
name: Terraform Validate and Scan
description: Terraform Validate
inputs:
  tf_state_gcs_bucket_name:
    required: true
    description: "TF State Bucket Name"
  tf_state_file_key_name:
    required: true
    description: "TF State File"
  workload_identity_provider:
    required: true
    description: "Workload identity provider for GCP"
  service_account:
    required: true
    description: "Service account to be used for GCP"
  working_directory:
    required: true
    description: "Working directory of root terraform module"
  token:
    required: false
    description: "GITHUB token"
    default: ''
  terraform_version:
    required: false
    description: "Terraform version"
    default: "1.7.5"
  gh_app_id:
    required: false
    description: "Github App ID"
  gh_app_private_key:
    required: false
    description: "Github App Private Key"

outputs:
  gcp_access_token:
    description: "Access token from the auth step"
    value: ${{ steps.auth.outputs.access_token }}

  credentials_file_path:
    description: "Credential file path from the auth step"
    value: ${{ steps.auth.outputs.credentials_file_path }}

runs:
  using: 'composite'
  steps:
    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v3
      with:
        terraform_version: ${{ inputs.terraform_version }}
        terraform_wrapper: false

    - name: GCP Auth
      id: auth
      uses: google-github-actions/auth@v2
      with:
        export_environment_variables: true
        create_credentials_file: true
        token_format: 'access_token'
        workload_identity_provider: ${{ inputs.workload_identity_provider }}
        service_account: ${{ inputs.service_account }}

    - name: 'Set up Cloud SDK'
      uses: 'google-github-actions/setup-gcloud@v2'
      with:
        version: '>= 363.0.0'

    - name: Get githubapp access token
      id: ghapp_access_token
      uses: actions/create-github-app-token@v1
      with:
        app-id: ${{ inputs.gh_app_id }}
        private-key: ${{ inputs.gh_app_private_key }}
        owner: "-cloud-foundations-org" # all gcp modules are under -cloud-foundations-org
    
    - name: Configure Git 
      run: |
        git config --global url."https://oauth2:${GH_token}@github.com".insteadOf https://github.com
      shell: bash
      env:
        GH_token: ${{ steps.ghapp_access_token.outputs.token }}

    - name: Initialize Terraform
      run: |
        terraform init \
          -backend-config="bucket=${{ inputs.tf_state_gcs_bucket_name }}" \
          -backend-config="prefix=${{ inputs.tf_state_file_key_name }}"
      shell: bash
      env:
        GOOGLE_OAUTH_ACCESS_TOKEN: ${{steps.auth.outputs.access_token}}
      working-directory: ${{ inputs.working_directory }}
