```yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql-config
  namespace: default
data:
  MYSQL_DATABASE: "my_database"
  MYSQL_USER: "my_user"
  MYSQL_PASSWORD: "my_password"
  MYSQL_ROOT_PASSWORD: "root_password"
```
