```yaml
version: '3.8'

services:
  web:
    image: my-web-app:latest
    ports:
      - "80:80"
    deploy:
      replicas: 3
      resources:
        limits:
          cpus: '0.50'
          memory: 512M
      restart_policy:
        condition: on-failure
    networks:
      - webnet

networks:
  webnet:
```
