name: CI Receipts
on:
  workflow_dispatch:
    inputs:
      receipt_context:
        description: 'The context in which a check-run update is called'
        required: false
  pull_request:
    types: ['opened', 'synchronize', 'reopened']
    branches: ['main']

permissions: write-all

jobs:
  get_ci_receipts:
    if: github.event.pull_request.head.ref != 'release-please--branches--main'
    runs-on: ubuntu-latest
    permissions:
      checks: write
      contents: write
    steps:
      - uses: actions/checkout@v4

      - uses: actions/create-github-app-token@v1
        id: app-token
        with:
          app-id: 893957
          private-key: ${{ secrets.TEST_KEY }}
          owner: test-org

      - uses: actions/checkout@v4

      - name: "CI Receipts"
        uses: test-org/receipts@feature/githubApp
        with:
          token: ${{ steps.app-token.outputs.token }}
          receipt_context: ${{ inputs.receipt_context }}
